package com.alpaomega1136.statsdroid.ui.theme

import androidx.compose.ui.graphics.Color

// Light Mode Tokens
val LightBackground = Color(0xFFF5F8FC)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFE8EEF6)
val LightPrimary = Color(0xFF006B83)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBCEEFF)
val LightOnPrimaryContainer = Color(0xFF001F28)
val LightSecondary = Color(0xFF4F5FC8)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0E0FF)
val LightOnSecondaryContainer = Color(0xFF07006B)
val LightTertiary = Color(0xFFB64D60)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightSuccess = Color(0xFF157A55)
val LightWarning = Color(0xFFA45A00)
val LightOnBackground = Color(0xFF171C22)
val LightOnSurface = Color(0xFF171C22)
val LightOnSurfaceVariant = Color(0xFF404852)
val LightOutline = Color(0xFF707883)

// Dark Mode Tokens
val DarkBackground = Color(0xFF07111F)
val DarkSurface = Color(0xFF0E1A2B)
val DarkSurfaceVariant = Color(0xFF17263A)
val DarkPrimary = Color(0xFF63D8FF)
val DarkOnPrimary = Color(0xFF003644)
val DarkPrimaryContainer = Color(0xFF004E63)
val DarkOnPrimaryContainer = Color(0xFFBCEEFF)
val DarkSecondary = Color(0xFFAEB8FF)
val DarkOnSecondary = Color(0xFF1C279B)
val DarkSecondaryContainer = Color(0xFF3647B0)
val DarkOnSecondaryContainer = Color(0xFFE0E0FF)
val DarkTertiary = Color(0xFFFF9AA8)
val DarkOnTertiary = Color(0xFF670024)
val DarkSuccess = Color(0xFF72D5A5)
val DarkWarning = Color(0xFFFFBE6B)
val DarkOnBackground = Color(0xFFE0E7F5)
val DarkOnSurface = Color(0xFFE0E7F5)
val DarkOnSurfaceVariant = Color(0xFFC0C8D6)
val DarkOutline = Color(0xFF8A92A0)

// Semantic Extension Colors
val SuccessGreen = Color(0xFF157A55)
val SuccessGreenDark = Color(0xFF72D5A5)
val WarningAmber = Color(0xFFA45A00)
val WarningAmberDark = Color(0xFFFFBE6B)